version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./todo_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    depends_on:
      - mongo

  frontend:
    build: ./todo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
